# Generated by Django 4.2.9 on 2024-01-16 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0003_watchlist_platfrom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='platfrom',
            new_name='platform',
        ),
    ]
